server:
  port: 8090


logging:
#  pattern:
#    console: "%-5level [%thread]: %message%n"
  level:
    root: INFO
    io:
      sapl: DEBUG
    org:
      springframework:
        web: INFO
        security: INFO

io:
  sapl:
    pdp:
      embedded:
        enabled: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
