io.sapl.pdp:
# The following lines show the default configuration and could be omitted.
# pdp-config-type may be RESOURCES (loading policies and configuration from bundles resources),
# DIRECTORY (loading policies and configuration from a folder on the filesystem),
# MULTI_DIRECTORY (multi-tenant with subdirectories), or BUNDLES (multi-tenant with .saplbundle files)
  embedded:
    pdp-config-type: RESOURCES
    # defines the path (in resources or filesystem respectively) for the pdp.json file with combining algorithm and variables
    config-path: /policies
    # defines the path (in resources or filesystem respectively) containing .sapl files with policies and policy sets
    policies-path: /policies
# The following options enable or disable different levels of logging for decisions.
#
# print-trace: true|false This is the most fine-grained explanation of a decision made
#                         by the PDP each individual calculation step is documented.
#                         The trace is in JSON format and may become very large.
#                         Recommended only as a last resort for troubleshooting.
    print-trace: false
# print-json-report: true|false This is a JSON report summarizing the applied algorithms
#                               and results of each evaluated policy (set) in the
#                               decision-making process. It includes lists of all errors and values
#                               of policy information point attributes encountered
#                               during the evaluation of each policy (set).
    print-json-report: false
# print-text-report: true|false This will log a human-readable textual report based on the
#                               same data as the 'print-json-report' option generates.
    print-text-report: true
# pretty-print-reports: true|false This option can enable formatting of JSON data while
#                                  printing JSON during reporting and tracing.
#                                  If it is intended to copy&paste JSON from the console-log
#                                  it is recommended to keep this turned off.
    pretty-print-reports: false
    
# The context path and port to use for this demo application
# (http://localhost:8080)
server:
  port: 8080
  servlet.context-path: /

spring:
  # do not show the default spring banner
  main.banner-mode: off
  jpa.open-in-view: false
  # Converts POST requests with _method=DELETE into actual DELETE requests.
  mvc.hiddenmethod.filter.enabled: true
# Set the log level to DEBUG or TRACE to get detailed information about the
# policy engine decision process.
logging.level:
  "[io.sapl]": INFO
  "[org.springframework]": WARN
